language: java
jdk:
 - oraclejdk7
before_install:
 - chmod +x gradlew
install:
 - mkdir $HOME/opt/wilma/repo/
script:
 - ./gradlew -b browsermob-proxy/build.gradle build createPom uploadArchives -x checkstyleMain -x checkstyleTest -PlocalRepository=file:///$HOME/opt/wilma/repo/ -PbuildNumber=TRAVIS_BUILD_NUMBER
 - ./gradlew build release -PlocalRepository=file:///$HOME/opt/wilma/repo/
 - ./gradlew -b wilma-mock/build.gradle build createPom uploadArchives -PbuildNumber=TRAVIS_BUILD_NUMBER
 - ./gradlew -b wilma-test/wilma-test-client/build.gradle build -x checkstyleMain -x checkstyleTest -PbuildNumber=TRAVIS_BUILD_NUMBER
 - ./gradlew -b wilma-test/wilma-test-server/build.gradle build -x checkstyleMain -x checkstyleTest -PbuildNumber=TRAVIS_BUILD_NUMBER
 - ./gradlew -b wilma-mock/build.gradle clean build createPom uploadArchives
 - ./gradlew -b wilma-functionaltest/build.gradle build
branches:
  only:
  - master
notifications:
  email:
  - tkohegyi2@gmail.com
